window.wordsA1 = [
    { word: "hello", translation: "سلام", definition: "used as a greeting", ex_en: "Hello! How are you?" },
    { word: "goodbye", translation: "خداحافظ", definition: "used when leaving someone", ex_en: "Goodbye, see you tomorrow!" },
    { word: "yes", translation: "بله", definition: "used to give an affirmative response", ex_en: "Yes, I like it." },
    { word: "no", translation: "خیر", definition: "used to give a negative response", ex_en: "No, I don't want it." },
    { word: "please", translation: "لطفاً", definition: "used to make a request more polite", ex_en: "Please help me." },
    { word: "thank you", translation: "ممنون", definition: "used to express gratitude", ex_en: "Thank you for the gift." },
    { word: "water", translation: "آب", definition: "a clear liquid that we drink", ex_en: "I need a glass of water." },
    { word: "food", translation: "غذا", definition: "something we eat to live", ex_en: "I like Italian food." },
    { word: "house", translation: "خانه", definition: "a building where people live", ex_en: "My house is big." },
    { word: "car", translation: "ماشین", definition: "a vehicle with four wheels", ex_en: "He drives a red car." },
    { word: "book", translation: "کتاب", definition: "something with pages that we read", ex_en: "I read a book every night." },
    { word: "school", translation: "مدرسه", definition: "a place where students learn", ex_en: "I go to school every day." },
    { word: "friend", translation: "دوست", definition: "a person you like and trust", ex_en: "She is my best friend." },
    { word: "family", translation: "خانواده", definition: "people related to you", ex_en: "I love my family." },
    { word: "name", translation: "نام", definition: "what someone or something is called", ex_en: "What is your name?" },
    { word: "day", translation: "روز", definition: "a period of 24 hours", ex_en: "Today is a good day." },
    { word: "night", translation: "شب", definition: "the time when it is dark", ex_en: "I sleep at night." },
    { word: "big", translation: "بزرگ", definition: "large in size", ex_en: "The elephant is big." },
    { word: "small", translation: "کوچک", definition: "little in size", ex_en: "The mouse is small." },
    { word: "happy", translation: "خوشحال", definition: "feeling pleasure or joy", ex_en: "I am happy today." }
];
