window.wordsA1 = [
    {
        word: "be (A1)",
        translation: "بودن",
        definition: "To exist.",
        example: "I want to be a teacher.",
        ex_trans: "من می‌خواهم یک معلم باشم.",
        collocation: "Be careful",
        coll_trans: "مراقب باش",
        coll_ex: "Be careful when you cross the street.",
        coll_ex_fa: "موقع عبور از خیابان مراقب باش.",
        phrasal_1: "Be back",
        ph1_trans: "برگشتن",
        ph1_ex: "I will be back in ten minutes.",
        ph1_ex_fa: "من تا ده دقیقه دیگر برمی‌گردم.",
        phrasal_2: "Be over",
        ph2_trans: "تمام شدن",
        ph2_ex: "The game will be over soon.",
        ph2_ex_fa: "بازی به زودی تمام خواهد شد."
    },
    {
        word: "have (A1)",
        translation: "داشتن",
        definition: "To possess something.",
        example: "I have a blue car.",
        ex_trans: "من یک ماشین آبی دارم.",
        collocation: "Have breakfast",
        coll_trans: "صبحانه خوردن",
        coll_ex: "What time do you have breakfast?",
        coll_ex_fa: "چه ساعتی صبحانه می‌خوری؟",
        phrasal_1: "Have to",
        ph1_trans: "مجبور بودن",
        ph1_ex: "I have to go to work now.",
        ph1_ex_fa: "من الان مجبورم به سر کار بروم.",
        phrasal_2: "Have on",
        ph2_trans: "پوشیدن (لباس)",
        ph2_ex: "She had a red hat on.",
        ph2_ex_fa: "او یک کلاه قرمز بر سر داشت."
    },
    {
        word: "do (A1)",
        translation: "انجام دادن",
        definition: "To perform an action.",
        example: "I do my homework.",
        ex_trans: "من تکالیفم را انجام می‌دهم.",
        collocation: "Do your best",
        coll_trans: "تمام تلاشت را بکن",
        coll_ex: "Don't worry, just do your best.",
        coll_ex_fa: "نگران نباش، فقط تمام تلاشت را بکن.",
        phrasal_1: "Do over",
        ph1_trans: "دوباره انجام دادن",
        ph1_ex: "This work is bad, do it over.",
        ph1_ex_fa: "این کار بد است، دوباره انجامش بده.",
        phrasal_2: "Do up",
        ph2_trans: "بستن (دکمه یا بند کفش)",
        ph2_ex: "Do up your coat, it's cold.",
        ph2_ex_fa: "دکمه‌های کتت را ببند، هوا سرد است."
    },
    {
        word: "say (A1)",
        translation: "گفتن",
        definition: "To speak words.",
        example: "Say hello to her.",
        ex_trans: "به او سلام بگو.",
        collocation: "Say a prayer",
        coll_trans: "دعا کردن",
        coll_ex: "They say a prayer before eating.",
        coll_ex_fa: "آن‌ها قبل از غذا خوردن دعا می‌کنند.",
        phrasal_1: "Say out",
        ph1_trans: "بلند گفتن",
        ph1_ex: "Say your name out so we can hear.",
        ph1_ex_fa: "نامت را بلند بگو تا بشنویم.",
        phrasal_2: "Say for",
        ph2_trans: "به نفع کسی حرف زدن",
        ph2_ex: "What can you say for your friend?",
        ph2_ex_fa: "چه حرفی داری که به نفع دوستت بزنی؟"
    },
    {
        word: "go (A1)",
        translation: "رفتن",
        definition: "To move to a place.",
        example: "I go to school.",
        ex_trans: "من به مدرسه می‌روم.",
        collocation: "Go home",
        coll_trans: "به خانه رفتن",
        coll_ex: "I am tired, let's go home.",
        coll_ex_fa: "خسته‌ام، بیا برویم خانه.",
        phrasal_1: "Go on",
        ph1_trans: "ادامه دادن",
        ph1_ex: "Please go on with your story.",
        ph1_ex_fa: "لطفاً به داستانت ادامه بده.",
        phrasal_2: "Go out",
        ph2_trans: "بیرون رفتن (تفریح)",
        ph2_ex: "Do you want to go out tonight?",
        ph2_ex_fa: "می‌خواهی امشب بریم بیرون؟"
    },
    {
        word: "get (A1)",
        translation: "گرفتن / شدن",
        definition: "To receive or become.",
        example: "I get happy today.",
        ex_trans: "من امروز خوشحال می‌شوم.",
        collocation: "Get ready",
        coll_trans: "آماده شدن",
        coll_ex: "Get ready for school.",
        coll_ex_fa: "برای مدرسه آماده شو.",
        phrasal_1: "Get up",
        ph1_trans: "بیدار شدن",
        ph1_ex: "I get up at 7 every day.",
        ph1_ex_fa: "من هر روز ساعت ۷ بیدار می‌شوم.",
        phrasal_2: "Get in",
        ph2_trans: "سوار شدن (ماشین)",
        ph2_ex: "Get in the car, we are late.",
        ph2_ex_fa: "سوار ماشین شو، دیرمان شده."
    },
    {
        word: "make (A1)",
        translation: "ساختن",
        definition: "To create something.",
        example: "I make a cake.",
        ex_trans: "من یک کیک درست می‌کنم.",
        collocation: "Make a mistake",
        coll_trans: "اشتباه کردن",
        coll_ex: "Everyone makes a mistake.",
        coll_ex_fa: "هر کسی اشتباه می‌کند.",
        phrasal_1: "Make up",
        ph1_trans: "ابداع کردن / آرایش کردن",
        ph1_ex: "He made up a story about a dragon.",
        ph1_ex_fa: "او داستانی درباره یک اژدها ابداع کرد.",
        phrasal_2: "Make sure",
        ph2_trans: "مطمئن شدن",
        ph2_ex: "Make sure the door is locked.",
        ph2_ex_fa: "مطمئن شو که در قفل است."
    },
    {
        word: "know (A1)",
        translation: "دانستن",
        definition: "To have info.",
        example: "I know the answer.",
        ex_trans: "من جواب را می‌دانم.",
        collocation: "Know well",
        coll_trans: "خوب شناختن",
        coll_ex: "I know this city very well.",
        coll_ex_fa: "من این شهر را خیلی خوب می‌شناسم.",
        phrasal_1: "Know of",
        ph1_trans: "اطلاع داشتن از وجود چیزی",
        ph1_ex: "I know of a good restaurant near here.",
        ph1_ex_fa: "من از وجود یک رستوران خوب این نزدیکی خبر دارم.",
        phrasal_2: "Know about",
        ph2_trans: "اطلاع داشتن درباره",
        ph2_ex: "What do you know about history?",
        ph2_ex_fa: "درباره تاریخ چه می‌دانی؟"
    },
    {
        word: "think (A1)",
        translation: "فکر کردن",
        definition: "To use the mind.",
        example: "I think it is good.",
        ex_trans: "فکر می‌کنم خوب است.",
        collocation: "Think about",
        coll_trans: "فکر کردن درباره",
        coll_ex: "Think about your future.",
        coll_ex_fa: "درباره آینده‌ات فکر کن.",
        phrasal_1: "Think over",
        ph1_trans: "به دقت فکر کردن",
        ph1_ex: "Think it over before you decide.",
        ph1_ex_fa: "قبل از تصمیم‌گیری، خوب درباره‌اش فکر کن.",
        phrasal_2: "Think up",
        ph2_trans: "ابداع کردن ایده",
        ph2_ex: "Can you think up a better plan?",
        ph2_ex_fa: "می‌توانی یک نقشه بهتر ابداع کنی؟"
    },
    {
        word: "take (A1)",
        translation: "گرفتن / بردن",
        definition: "To reach for something.",
        example: "Take your umbrella.",
        ex_trans: "چترت را بردار.",
        collocation: "Take a photo",
        coll_trans: "عکس گرفتن",
        coll_ex: "Can you take a photo of me?",
        coll_ex_fa: "می‌توانی از من عکس بگیری؟",
        phrasal_1: "Take off",
        ph1_trans: "درآوردن لباس / پرواز هواپیما",
        ph1_ex: "Take off your shoes.",
        ph1_ex_fa: "کفش‌هایت را درآور.",
        phrasal_2: "Take out",
        ph2_trans: "بیرون بردن",
        ph2_ex: "Don't forget to take out the trash.",
        ph2_ex_fa: "فراموش نکن آشغال‌ها را بیرون ببری."
    }
];
    {
        word: "water (A1)",
        translation: "آب",
        definition: "A clear liquid to drink.",
        example: "Can I have some water?",
        ex_trans: "می‌توانم مقداری آب داشته باشم؟",
        collocation: "Drinking water",
        coll_trans: "آب آشامیدنی",
        coll_ex: "Is this drinking water safe?",
        coll_ex_fa: "آیا این آب آشامیدنی سالم است؟",
        phrasal_1: "Water down",
        ph1_trans: "رقیق کردن / ضعیف کردن",
        ph1_ex: "They watered down the juice.",
        ph1_ex_fa: "آن‌ها آبمیوه را رقیق کردند (آب قاطی کردند).",
        phrasal_2: "Under water",
        ph2_trans: "زیر آب",
        ph2_ex: "He can stay under water for a minute.",
        ph2_ex_fa: "او می‌تواند یک دقیقه زیر آب بماند."
    },
    {
        word: "food (A1)",
        translation: "غذا",
        definition: "Things you eat.",
        example: "The food is delicious.",
        ex_trans: "غذا لذیذ است.",
        collocation: "Fast food",
        coll_trans: "غذای آماده",
        coll_ex: "I don't like fast food.",
        coll_ex_fa: "من غذای آماده دوست ندارم.",
        phrasal_1: "Food for thought",
        ph1_trans: "چیزی که آدم را به فکر فرو می‌برد",
        ph1_ex: "Your idea gave me food for thought.",
        ph1_ex_fa: "ایده تو مرا به فکر فرو برد.",
        phrasal_2: "Food poison",
        ph2_trans: "مسمومیت غذایی",
        ph2_ex: "I got food poisoning from that fish.",
        ph2_ex_fa: "من از آن ماهی دچار مسمومیت غذایی شدم."
    },
    {
        word: "friend (A1)",
        translation: "دوست",
        definition: "Someone you like and know.",
        example: "She is my best friend.",
        ex_trans: "او بهترین دوست من است.",
        collocation: "Make friends",
        coll_trans: "دوست پیدا کردن",
        coll_ex: "It is easy to make friends here.",
        coll_ex_fa: "اینجا دوست پیدا کردن آسان است.",
        phrasal_1: "Boyfriend",
        ph1_trans: "دوست پسر",
        ph1_ex: "Does she have a boyfriend?",
        ph1_ex_fa: "آیا او دوست پسر دارد؟",
        phrasal_2: "Girlfriend",
        ph2_trans: "دوست دختر",
        ph2_ex: "He is buying a gift for his girlfriend.",
        ph2_ex_fa: "او دارد برای دوست‌دخترش هدیه می‌خرد."
    },
    {
        word: "house (A1)",
        translation: "خانه",
        definition: "A building to live in.",
        example: "Our house is big.",
        ex_trans: "خانه ما بزرگ است.",
        collocation: "Guesthouse",
        coll_trans: "مسافرخانه / مهمان‌سرا",
        coll_ex: "We stayed in a small guesthouse.",
        coll_ex_fa: "ما در یک مهمان‌سرای کوچک ماندیم.",
        phrasal_1: "House keep",
        ph1_trans: "خانه‌داری کردن",
        ph1_ex: "She is very good at housekeeping.",
        ph1_ex_fa: "او در خانه‌داری خیلی خوب است.",
        phrasal_2: "Full house",
        ph2_trans: "خانه پر از جمعیت",
        ph2_ex: "We had a full house on my birthday.",
        ph2_ex_fa: "در روز تولدم، خانه‌مان پر از جمعیت بود."
    },
    {
        word: "car (A1)",
        translation: "ماشین",
        definition: "A vehicle with four wheels.",
        example: "I drive my car.",
        ex_trans: "من با ماشینم رانندگی می‌کنم.",
        collocation: "Used car",
        coll_trans: "ماشین دست‌دوم",
        coll_ex: "I want to buy a used car.",
        coll_ex_fa: "می‌خواهم یک ماشین دست‌دوم بخرم.",
        phrasal_1: "Car park",
        ph1_trans: "پارکینگ",
        ph1_ex: "Where is the nearest car park?",
        ph1_ex_fa: "نزدیک‌ترین پارکینگ کجاست؟",
        phrasal_2: "By car",
        ph2_trans: "با ماشین",
        ph2_ex: "We went to the beach by car.",
        ph2_ex_fa: "ما با ماشین به ساحل رفتیم."
    },
    {
        word: "school (A1)",
        translation: "مدرسه",
        definition: "A place for students.",
        example: "I go to school by bus.",
        ex_trans: "من با اتوبوس به مدرسه می‌روم.",
        collocation: "High school",
        coll_trans: "دبیرستان",
        coll_ex: "He is a student in high school.",
        coll_ex_fa: "او دانش‌آموز دبیرستان است.",
        phrasal_1: "At school",
        ph1_trans: "در مدرسه",
        ph1_ex: "The children are at school now.",
        ph1_ex_fa: "بچه‌ها الان در مدرسه هستند.",
        phrasal_2: "Primary school",
        ph2_trans: "مدرسه ابتدایی",
        ph2_ex: "My brother goes to primary school.",
        ph2_ex_fa: "برادرم به مدرسه ابتدایی می‌رود."
    },
    {
        word: "teacher (A1)",
        translation: "معلم",
        definition: "A person who teaches.",
        example: "My teacher is kind.",
        ex_trans: "معلم من مهربان است.",
        collocation: "English teacher",
        coll_trans: "معلم انگلیسی",
        coll_ex: "I have a great English teacher.",
        coll_ex_fa: "من یک معلم انگلیسی عالی دارم.",
        phrasal_1: "Teacher's pet",
        ph1_trans: "سوگلی معلم",
        ph1_ex: "She is always the teacher's pet.",
        ph1_ex_fa: "او همیشه سوگلی معلم است.",
        phrasal_2: "Head teacher",
        ph2_trans: "مدیر مدرسه",
        ph2_ex: "The head teacher is in his office.",
        ph2_ex_fa: "مدیر مدرسه در دفترش است."
    },
    {
        word: "hand (A1)",
        translation: "دست",
        definition: "The part at the end of the arm.",
        example: "Wash your hands.",
        ex_trans: "دست‌هایت را بشوی.",
        collocation: "Left hand",
        coll_trans: "دست چپ",
        coll_ex: "He writes with his left hand.",
        coll_ex_fa: "او با دست چپش می‌نویسد.",
        phrasal_1: "Hand in",
        ph1_trans: "تحویل دادن",
        ph1_ex: "Please hand in your papers.",
        ph1_ex_fa: "لطفاً ورقه‌هایتان را تحویل دهید.",
        phrasal_2: "Hand out",
        ph2_trans: "توزیع کردن",
        ph2_ex: "He is handing out flyers.",
        ph2_ex_fa: "او دارد تراکت پخش می‌کند."
    },
    {
        word: "eye (A1)",
        translation: "چشم",
        definition: "What you see with.",
        example: "She has green eyes.",
        ex_trans: "او چشم‌های سبز دارد.",
        collocation: "Close your eyes",
        coll_trans: "چشم‌هایت را ببند",
        coll_ex: "Close your eyes and make a wish.",
        coll_ex_fa: "چشم‌هایت را ببند و آرزو کن.",
        phrasal_1: "Eye contact",
        ph1_trans: "ارتباط چشمی",
        ph1_ex: "Try to make eye contact.",
        ph1_ex_fa: "سعی کن ارتباط چشمی برقرار کنی.",
        phrasal_2: "Keep an eye on",
        ph2_trans: "مراقب چیزی بودن",
        ph2_ex: "Keep an eye on the baby.",
        ph2_ex_fa: "مراقب نوزاد باش."
    },
    {
        word: "money (A1)",
        translation: "پول",
        definition: "Coins and notes for buying.",
        example: "I don't have enough money.",
        ex_trans: "من پول کافی ندارم.",
        collocation: "Save money",
        coll_trans: "پس‌انداز کردن",
        coll_ex: "I am trying to save money.",
        coll_ex_fa: "دارم سعی می‌کنم پول پس‌انداز کنم.",
        phrasal_1: "Pocket money",
        ph1_trans: "پول تو جیبی",
        ph1_ex: "How much pocket money do you get?",
        ph1_ex_fa: "چقدر پول تو جیبی می‌گیری؟",
        phrasal_2: "Make money",
        ph2_trans: "درآمد داشتن",
        ph2_ex: "He makes money by selling books.",
        ph2_ex_fa: "او با فروختن کتاب پول درمی‌آورد."
    }
    {
        word: "work (A1)",
        translation: "کار کردن",
        definition: "To do a job or task.",
        example: "I work in an office.",
        ex_trans: "من در یک اداره کار می‌کنم.",
        collocation: "Hard work",
        coll_trans: "کار سخت",
        coll_ex: "Success needs hard work.",
        coll_ex_fa: "موفقیت به کار سخت نیاز دارد.",
        phrasal_1: "Work out",
        ph1_trans: "ورزش کردن / حل شدن",
        ph1_ex: "I work out at the gym.",
        ph1_ex_fa: "من در باشگاه ورزش می‌کنم.",
        phrasal_2: "Work on",
        ph2_trans: "روی چیزی کار کردن",
        ph2_ex: "I am working on a new project.",
        ph2_ex_fa: "من دارم روی یک پروژه جدید کار می‌کنم."
    },
    {
        word: "call (A1)",
        translation: "تماس گرفتن / صدا زدن",
        definition: "To phone someone or shout.",
        example: "Call me tonight.",
        ex_trans: "امشب به من زنگ بزن.",
        collocation: "Phone call",
        coll_trans: "تماس تلفنی",
        coll_ex: "I have an important phone call.",
        coll_ex_fa: "من یک تماس تلفنی مهم دارم.",
        phrasal_1: "Call back",
        ph1_trans: "دوباره زنگ زدن",
        ph1_ex: "I will call you back later.",
        ph1_ex_fa: "بعداً دوباره بهت زنگ می‌زنم.",
        phrasal_2: "Call off",
        ph2_trans: "لغو کردن",
        ph2_ex: "They called off the meeting.",
        ph2_ex_fa: "آن‌ها جلسه را لغو کردند."
    },
    {
        word: "try (A1)",
        translation: "تلاش کردن / امتحان کردن",
        definition: "To make an effort.",
        example: "Try to speak English.",
        ex_trans: "سعی کن انگلیسی صحبت کنی.",
        collocation: "Give it a try",
        coll_trans: "امتحانش کن",
        coll_ex: "If you're not sure, give it a try.",
        coll_ex_fa: "اگر مطمئن نیستی، امتحانش کن.",
        phrasal_1: "Try on",
        ph1_trans: "پرو کردن (لباس)",
        ph1_ex: "Can I try on this jacket?",
        ph1_ex_fa: "می‌توانم این ژاکت را پرو کنم؟",
        phrasal_2: "Try out",
        ph2_trans: "تست کردن (دستگاه یا ایده)",
        ph2_ex: "We are trying out a new car.",
        ph2_ex_fa: "ما داریم یک ماشین جدید را تست می‌کنیم."
    },
    {
        word: "ask (A1)",
        translation: "پرسیدن / درخواست کردن",
        definition: "To say something to get info.",
        example: "Ask him for help.",
        ex_trans: "از او کمک بخواه.",
        collocation: "Ask a question",
        coll_trans: "سوال پرسیدن",
        coll_ex: "May I ask a question?",
        coll_ex_fa: "می‌توانم یک سوال بپرسم؟",
        phrasal_1: "Ask out",
        ph1_trans: "دعوت به قرار عاشقانه",
        ph1_ex: "He finally asked her out.",
        ph1_ex_fa: "او بالاخره ازش خواست که با هم برن سر قرار.",
        phrasal_2: "Ask for",
        ph2_trans: "درخواست کردن چیزی",
        ph2_ex: "The child asked for some candy.",
        ph2_ex_fa: "کودک مقداری شکلات خواست."
    },
    {
        word: "feel (A1)",
        translation: "احساس کردن",
        definition: "To experience an emotion.",
        example: "I feel very happy today.",
        ex_trans: "امروز احساس خیلی خوبی دارم.",
        collocation: "Feel better",
        coll_trans: "احساس بهبودی",
        coll_ex: "I hope you feel better soon.",
        coll_ex_fa: "امیدوارم زودتر حالت بهتر شود.",
        phrasal_1: "Feel like",
        ph1_trans: "حوصله/میل به چیزی داشتن",
        ph1_ex: "I feel like a cup of tea.",
        ph1_ex_fa: "میلم به یک فنجان چای است.",
        phrasal_2: "Feel for",
        ph2_trans: "همدردی کردن با کسی",
        ph2_ex: "I really feel for him in this situation.",
        ph2_ex_fa: "من واقعاً در این شرایط با او همدردی می‌کنم."
    },
    {
        word: "leave (A1)",
        translation: "ترک کردن / خارج شدن",
        definition: "To go away from a place.",
        example: "I leave home at 8 AM.",
        ex_trans: "من ساعت ۸ صبح خانه را ترک می‌کنم.",
        collocation: "Leave message",
        coll_trans: "پیغام گذاشتن",
        coll_ex: "Please leave a message after the beep.",
        coll_ex_fa: "لطفاً بعد از صدای بوق پیغام بگذارید.",
        phrasal_1: "Leave out",
        ph1_trans: "حذف کردن / نادیده گرفتن",
        ph1_ex: "Don't leave me out of the game.",
        ph1_ex_fa: "مرا از بازی کنار نگذارید (نادیده نگیرید).",
        phrasal_2: "Leave behind",
        ph2_trans: "جا گذاشتن",
        ph2_ex: "I left my umbrella behind in the bus.",
        ph2_ex_fa: "من چترم را در اتوبوس جا گذاشتم."
    },
    {
        word: "keep (A1)",
        translation: "نگه داشتن / ادامه دادن",
        definition: "To continue having or doing.",
        example: "Keep your room clean.",
        ex_trans: "اتاق خود را تمیز نگه دار.",
        collocation: "Keep calm",
        coll_trans: "آرام ماندن",
        coll_ex: "Keep calm and stay focused.",
        coll_ex_fa: "آرام بمان و تمرکزت را حفظ کن.",
        phrasal_1: "Keep on",
        ph1_trans: "ادامه دادن (پشتکار)",
        ph1_ex: "Keep on trying, don't give up.",
        ph1_ex_fa: "به تلاش کردن ادامه بده، تسلیم نشو.",
        phrasal_2: "Keep away",
        ph2_trans: "دور نگه داشتن",
        ph2_ex: "Keep away from the fire.",
        ph2_ex_fa: "از آتش دور بمان."
    },
    {
        word: "start (A1)",
        translation: "شروع کردن",
        definition: "To begin something.",
        example: "Let's start the lesson.",
        ex_trans: "بیا درس را شروع کنیم.",
        collocation: "Start a fire",
        coll_trans: "آتش روشن کردن",
        coll_ex: "They started a fire to keep warm.",
        coll_ex_fa: "آن‌ها برای گرم ماندن آتش روشن کردند.",
        phrasal_1: "Start up",
        ph1_trans: "راه اندازی کردن (موتور یا بیزنس)",
        ph1_ex: "He wants to start up a new company.",
        ph1_ex_fa: "او می‌خواهد یک شرکت جدید راه بیندازد.",
        phrasal_2: "Start over",
        ph2_trans: "دوباره از اول شروع کردن",
        ph2_ex: "I made a mistake, can I start over?",
        ph2_ex_fa: "اشتباه کردم، می‌توانم از اول شروع کنم؟"
    },
    {
        word: "show (A1)",
        translation: "نشان دادن",
        definition: "To let someone see.",
        example: "Show me your new car.",
        ex_trans: "ماشین جدیدت را به من نشان بده.",
        collocation: "TV show",
        coll_trans: "برنامه تلویزیونی",
        coll_ex: "My favorite TV show is on now.",
        coll_ex_fa: "برنامه تلویزیونی مورد علاقه‌ام الان در حال پخش است.",
        phrasal_1: "Show up",
        ph1_trans: "حاضر شدن / پیدا شدن",
        ph1_ex: "He didn't show up for the meeting.",
        ph1_ex_fa: "او برای جلسه حاضر نشد.",
        phrasal_2: "Show off",
        ph2_trans: "پز دادن / خودنمایی",
        ph2_ex: "He likes to show off his new watch.",
        ph2_ex_fa: "او دوست دارد ساعت جدیدش را پز بدهد."
    },
    {
        word: "hear (A1)",
        translation: "شنیدن",
        definition: "To receive sound with ears.",
        example: "Can you hear me?",
        ex_trans: "صدای مرا می‌شنوی؟",
        collocation: "Hear a noise",
        coll_trans: "شنیدن سر و صدا",
        coll_ex: "I heard a strange noise last night.",
        coll_ex_fa: "دیشب صدای عجیبی شنیدم.",
        phrasal_1: "Hear from",
        ph1_trans: "بی‌خبر نماندن از کسی",
        ph1_ex: "I haven't heard from him for weeks.",
        ph1_ex_fa: "هفته‌هاست که از او بی‌خبرم.",
        phrasal_2: "Hear of",
        ph2_trans: "شنیدن درباره وجود چیزی",
        ph2_ex: "Have you ever heard of this place?",
        ph2_ex_fa: "آیا تا به حال اسم این مگان را شنیده‌ای؟"
    }
    {
        word: "play (A1)",
        translation: "بازی کردن / نواختن",
        definition: "To do an activity for fun.",
        example: "Children play in the park.",
        ex_trans: "بچه‌ها در پارک بازی می‌کنند.",
        collocation: "Play music",
        coll_trans: "موسیقی نواختن",
        coll_ex: "Can you play the piano?",
        coll_ex_fa: "آیا می‌توانی پیانو بنوازی؟",
        phrasal_1: "Play along",
        ph1_trans: "همکاری کردن (ظاهری)",
        ph1_ex: "I decided to play along with his joke.",
        ph1_ex_fa: "تصمیم گرفتم با شوخی‌اش همراهی کنم.",
        phrasal_2: "Play out",
        ph2_trans: "اتفاق افتادن / رقم خوردن",
        ph2_ex: "We will see how the game plays out.",
        ph2_ex_fa: "خواهیم دید که بازی چطور رقم می‌خورد."
    },
    {
        word: "live (A1)",
        translation: "زندگی کردن",
        definition: "To have your home in a place.",
        example: "I live in a small town.",
        ex_trans: "من در یک شهر کوچک زندگی می‌کنم.",
        collocation: "Live alone",
        coll_trans: "تنها زندگی کردن",
        coll_ex: "She lives alone in London.",
        coll_ex_fa: "او در لندن تنها زندگی می‌کند.",
        phrasal_1: "Live on",
        ph1_trans: "ادامه زندگی با (هزینه/غذا)",
        ph1_ex: "They live on very little money.",
        ph1_ex_fa: "آن‌ها با پول خیلی کمی زندگی می‌کنند.",
        phrasal_2: "Live up to",
        ph2_trans: "برآورده کردن (انتظار)",
        ph2_ex: "The hotel didn't live up to our expectations.",
        ph2_ex_fa: "هتل انتظارات ما را برآورده نکرد."
    },
    {
        word: "help (A1)",
        translation: "کمک کردن",
        definition: "To make something easier for someone.",
        example: "Can you help me with this bag?",
        ex_trans: "می‌توانی در حمل این ساک به من کمک کنی؟",
        collocation: "Help out",
        coll_trans: "کمک رساندن",
        coll_ex: "Thanks for helping me out.",
        coll_ex_fa: "ممنون که به دادم رسیدی (کمکم کردی).",
        phrasal_1: "Help forward",
        ph1_trans: "پیش بردن کار",
        ph1_ex: "Your advice helped me forward.",
        ph1_ex_fa: "نصیحت تو کار مرا پیش برد.",
        phrasal_2: "Can't help",
        ph2_trans: "دست خود نبودن",
        ph2_ex: "I couldn't help laughing.",
        ph2_ex_fa: "نمی‌توانستم جلوی خنده‌ام را بگیرم."
    },
    {
        word: "move (A1)",
        translation: "حرکت کردن / جابجا شدن",
        definition: "To change position.",
        example: "Don't move, stay there.",
        ex_trans: "حرکت نکن، همان‌جا بمان.",
        collocation: "Move house",
        coll_trans: "اسباب‌کشی کردن",
        coll_ex: "We are moving house next week.",
        coll_ex_fa: "ما هفته آینده اسباب‌کشی می‌کنیم.",
        phrasal_1: "Move on",
        ph1_trans: "گذشتن از گذشته / ادامه دادن",
        ph1_ex: "It's time to move on with your life.",
        ph1_ex_fa: "وقت آن است که به زندگی‌ات ادامه بدهی (از گذشته بگذری).",
        phrasal_2: "Move in",
        ph2_trans: "ساکن شدن در خانه جدید",
        ph2_ex: "Our new neighbors moved in yesterday.",
        ph2_ex_fa: "همسایه‌های جدیدمان دیروز ساکن شدند."
    },
    {
        word: "run (A1)",
        translation: "دویدن / اداره کردن",
        definition: "To move fast with legs.",
        example: "I run every morning.",
        ex_trans: "من هر روز صبح می‌دوم.",
        collocation: "Run a business",
        coll_trans: "اداره کردن یک بیزنس",
        coll_ex: "She runs a small cafe.",
        coll_ex_fa: "او یک کافه کوچک را اداره می‌کند.",
        phrasal_1: "Run out of",
        ph1_trans: "تمام کردن (ذخیره)",
        ph1_ex: "We ran out of milk.",
        ph1_ex_fa: "شیرمان تمام شد.",
        phrasal_2: "Run away",
        ph2_trans: "فرار کردن",
        ph2_ex: "Don't run away from your problems.",
        ph2_ex_fa: "از مشکلاتت فرار نکن."
    },
    {
        word: "bring (A1)",
        translation: "آوردن",
        definition: "To take something to a place.",
        example: "Bring your books to class.",
        ex_trans: "کتاب‌هایتان را به کلاس بیاورید.",
        collocation: "Bring luck",
        coll_trans: "شانس آوردن",
        coll_ex: "This ring brings me luck.",
        coll_ex_fa: "این انگشتر برایم شانس می‌آورد.",
        phrasal_1: "Bring back",
        ph1_trans: "پس آوردن / به یاد آوردن",
        ph1_ex: "Please bring back my bike.",
        ph1_ex_fa: "لطفاً دوچرخه‌ام را پس بیاور.",
        phrasal_2: "Bring up",
        ph2_trans: "مطرح کردن بحث / تربیت فرزند",
        ph2_ex: "She was brought up in a small village.",
        ph2_ex_fa: "او در یک روستای کوچک بزرگ شده بود (تربیت شده بود)."
    },
    {
        word: "happen (A1)",
        translation: "اتفاق افتادن",
        definition: "To take place.",
        example: "What happened here?",
        ex_trans: "اینجا چه اتفاقی افتاد؟",
        collocation: "Accident happen",
        coll_trans: "رخ دادن حادثه",
        coll_ex: "Accidents can happen at any time.",
        coll_ex_fa: "حوادث هر لحظه ممکن است رخ دهند.",
        phrasal_1: "Happen to",
        ph1_trans: "بر سر کسی آمدن",
        ph1_ex: "What happened to your arm?",
        ph1_ex_fa: "چه بلایی سر بازویت آمد؟",
        phrasal_2: "Happen on",
        ph2_trans: "اتفاقی یافتن",
        ph2_ex: "I happened on this shop by chance.",
        ph2_ex_fa: "اتفاقی به این مغازه برخورد کردم."
    },
    {
        word: "sit (A1)",
        translation: "نشستن",
        definition: "To rest on a chair.",
        example: "Sit down on the chair.",
        ex_trans: "روی صندلی بنشین.",
        collocation: "Sit still",
        coll_trans: "بی‌حرکت نشستن",
        coll_ex: "Please sit still for a moment.",
        coll_ex_fa: "لطفاً یک لحظه بی‌حرکت بنشین.",
        phrasal_1: "Sit in",
        ph1_trans: "شرکت کردن (به عنوان تماشاچی)",
        ph1_ex: "Can I sit in on your class?",
        ph1_ex_fa: "می‌توانم (به عنوان مستمع آزاد) در کلاس شما بنشینم؟",
        phrasal_2: "Sit up",
        ph2_trans: "صاف نشستن / بیدار ماندن",
        ph2_ex: "She sat up late watching a movie.",
        ph2_ex_fa: "او تا دیر وقت برای دیدن فیلم بیدار نشست."
    },
    {
        word: "stand (A1)",
        translation: "ایستادن / تحمل کردن",
        definition: "To be on your feet.",
        example: "Stand up, please.",
        ex_trans: "لطفاً بلند شوید.",
        collocation: "Stand tall",
        coll_trans: "با اعتماد به نفس ایستادن",
        coll_ex: "Always stand tall and be proud.",
        coll_ex_fa: "همیشه با سربلندی و اعتماد به نفس بایست.",
        phrasal_1: "Stand by",
        ph1_trans: "آماده‌باش بودن / حمایت کردن",
        ph1_ex: "I will stand by you forever.",
        ph1_ex_fa: "من همیشه در کنار تو (حامی تو) خواهم بود.",
        phrasal_2: "Stand out",
        ph2_trans: "متمایز بودن / تو چشم بودن",
        ph2_ex: "Her bright red hair makes her stand out.",
        ph2_ex_fa: "موی قرمز درخشانش او را متمایز می‌کند."
    },
    {
        word: "lose (A1)",
        translation: "گم کردن / باختن",
        definition: "To not have something anymore.",
        example: "I lost my keys.",
        ex_trans: "من کلیدهایم را گم کردم.",
        collocation: "Lose weight",
        coll_trans: "وزن کم کردن",
        coll_ex: "I want to lose some weight.",
        coll_ex_fa: "می‌خواهم مقداری وزن کم کنم.",
        phrasal_1: "Lose out",
        ph1_trans: "متضرر شدن / فرصت از دست دادن",
        ph1_ex: "You will lose out if you don't act now.",
        ph1_ex_fa: "اگر الان اقدام نکنی، فرصت را از دست می‌دهی.",
        phrasal_2: "Lose it",
        ph2_trans: "کنترل اعصاب را از دست دادن",
        ph2_ex: "He completely lost it and started shouting.",
        ph2_ex_fa: "او کاملاً کنترلش را از دست داد و شروع به فریاد زدن کرد."
    }
