window.wordsA1 = [
  {
    word: "Experience",
    translation: "تجربه",
    definition_en: "Things that you do in your life.",
    collocation: "Work experience",
    collocation_fa: "تجربه کاری",
    collocation_example: "I need some work experience.",
    collocation_example_fa: "من به کمی تجربه کاری نیاز دارم.",
    pv1: "Go through",
    pv1_fa: "تجربه کردن / گذراندن",
    pv1_example: "He is going through a hard day.",
    pv1_example_fa: "او دارد روز سختی را می‌گذراند.",
    pv2: "Pick up",
    pv2_fa: "یاد گرفتن (تجربی)",
    pv2_example: "You can pick up skills at work.",
    pv2_example_fa: "تو می‌توانی مهارت‌ها را در کار یاد بگیری."
  },
  {
    word: "Ability",
    translation: "توانایی",
    definition_en: "Being able to do something well.",
    collocation: "Natural ability",
    collocation_fa: "توانایی ذاتی",
    collocation_example: "She has a natural ability for music.",
    collocation_example_fa: "او توانایی ذاتی در موسیقی دارد.",
    pv1: "Build up",
    pv1_fa: "تقویت کردن / افزایش دادن",
    pv1_example: "You should build up your abilities.",
    pv1_example_fa: "تو باید توانایی‌هایت را تقویت کنی.",
    pv2: "Work on",
    pv2_fa: "کار کردن روی چیزی",
    pv2_example: "I need to work on my speaking ability.",
    pv2_example_fa: "من باید روی توانایی صحبتم کار کنم."
  },
  {
    word: "Advice",
    translation: "نصیحت / توصیه",
    definition_en: "Words to help someone with a problem.",
    collocation: "Take advice",
    collocation_fa: "نصیحت گوش کردن",
    collocation_example: "You should take my advice.",
    collocation_example_fa: "تو باید به توصیه من گوش کنی.",
    pv1: "Listen to",
    pv1_fa: "گوش دادن به",
    pv1_example: "Listen to your doctor's advice.",
    pv1_example_fa: "به توصیه دکترت گوش کن.",
    pv2: "Give out",
    pv2_fa: "توزیع کردن / دادن",
    pv2_example: "He gives out free advice to everyone.",
    pv2_example_fa: "او به همه توصیه‌های رایگان می‌دهد."
  },
  {
    word: "Amount",
    translation: "مقدار",
    definition_en: "How much of something there is.",
    collocation: "Small amount",
    collocation_fa: "مقدار کم",
    collocation_example: "Add a small amount of salt.",
    collocation_example_fa: "مقدار کمی نمک اضافه کن.",
    pv1: "Add up",
    pv1_fa: "جمع زدن / بالغ شدن بر",
    pv1_example: "The costs add up to a large amount.",
    pv1_example_fa: "هزینه‌ها به مقدار زیادی بالغ می‌شود.",
    pv2: "Cut down",
    pv2_fa: "کاهش دادن مقدار مصرف",
    pv2_example: "Cut down the amount of sugar you eat.",
    pv2_example_fa: "مقدار شکری که می‌خوری را کاهش بده."
  },
  {
    word: "Answer",
    translation: "پاسخ / جواب",
    definition_en: "Something you say when someone asks a question.",
    collocation: "Correct answer",
    collocation_fa: "پاسخ صحیح",
    collocation_example: "What is the correct answer?",
    collocation_example_fa: "پاسخ صحیح چیست؟",
    pv1: "Write down",
    pv1_fa: "یادداشت کردن",
    pv1_example: "Write down your answer on paper.",
    pv1_example_fa: "پاسخت را روی کاغذ یادداشت کن.",
    pv2: "Talk back",
    pv2_fa: "جواب پس دادن (بی‌ادبانه)",
    pv2_example: "Don't talk back to your teacher.",
    pv2_example_fa: "به معلمت جواب پس نده."
  },
  {
    word: "Area",
    translation: "منطقه / ناحیه",
    definition_en: "A part of a place or a city.",
    collocation: "Quiet area",
    collocation_fa: "منطقه آرام",
    collocation_example: "We live in a quiet area.",
    collocation_example_fa: "ما در یک منطقه آرام زندگی می‌کنیم.",
    pv1: "Move to",
    pv1_fa: "نقل مکان کردن به",
    pv1_example: "They moved to a new area.",
    pv1_example_fa: "آن‌ها به یک منطقه جدید نقل مکان کردند.",
    pv2: "Clean up",
    pv2_fa: "تمیز کردن یک محیط",
    pv2_example: "We need to clean up this area.",
    pv2_example_fa: "ما باید این منطقه را تمیز کنیم."
  },
  {
    word: "Art",
    translation: "هنر",
    definition_en: "Making beautiful things like paintings.",
    collocation: "Modern art",
    collocation_fa: "هنر مدرن",
    collocation_example: "I like modern art.",
    collocation_example_fa: "من هنر مدرن را دوست دارم.",
    pv1: "Sketch out",
    pv1_fa: "طراحی کردن اولیه",
    pv1_example: "Sketch out your art idea first.",
    pv1_example_fa: "اول ایده هنری‌ات را طراحی کن.",
    pv2: "Show off",
    pv2_fa: "به نمایش گذاشتن / پز دادن",
    pv2_example: "She wants to show off her art.",
    pv2_example_fa: "او می‌خواهد هنر خود را به نمایش بگذارد."
  },
  {
    word: "Article",
    translation: "مقاله",
    definition_en: "A piece of writing in a newspaper.",
    collocation: "Read an article",
    collocation_fa: "خواندن یک مقاله",
    collocation_example: "I read an article about health.",
    collocation_example_fa: "من مقاله‌ای درباره سلامتی خواندم.",
    pv1: "Look through",
    pv1_fa: "روزنامه یا مقاله را سریع نگاه کردن",
    pv1_example: "Look through the article for names.",
    pv1_example_fa: "مقاله را برای پیدا کردن نام‌ها سریع نگاه کن.",
    pv2: "Cut out",
    pv2_fa: "بریدن (از مجله یا روزنامه)",
    pv2_example: "Cut out the article from the paper.",
    pv2_example_fa: "مقاله را از روزنامه جدا کن (ببر)."
  },
  {
    word: "Attention",
    translation: "توجه",
    definition_en: "Looking or listening carefully.",
    collocation: "Pay attention",
    collocation_fa: "توجه کردن",
    collocation_example: "Please pay attention to me.",
    collocation_example_fa: "لطفاً به من توجه کنید.",
    pv1: "Focus on",
    pv1_fa: "تمرکز کردن روی",
    pv1_example: "Focus on the lesson now.",
    pv1_example_fa: "الان روی درس تمرکز کن.",
    pv2: "Call for",
    pv2_fa: "فراخواندن / طلب کردن توجه",
    pv2_example: "The teacher called for attention.",
    pv2_example_fa: "معلم خواستار توجه شد."
  },
  {
    word: "Baby",
    translation: "نوزاد / کودک",
    definition_en: "A very young child.",
    collocation: "Newborn baby",
    collocation_fa: "نوزاد تازه متولد شده",
    collocation_example: "The newborn baby is sleeping.",
    collocation_example_fa: "نوزاد تازه متولد شده در حال خواب است.",
    pv1: "Look after",
    pv1_fa: "مراقبت کردن از",
    pv1_example: "Can you look after the baby?",
    pv1_example_fa: "می‌توانی از نوزاد مراقبت کنی؟",
    pv2: "Wake up",
    pv2_fa: "بیدار کردن / شدن",
    pv2_example: "Don't wake up the baby.",
    pv2_example_fa: "نوزاد را بیدار نکن."
  },
  {
    word: "Back",
    translation: "پشت / عقب",
    definition_en: "The part of your body behind you.",
    collocation: "Back pain",
    collocation_fa: "کمر درد",
    collocation_example: "He has bad back pain.",
    collocation_example_fa: "او کمردرد شدیدی دارد.",
    pv1: "Go back",
    pv1_fa: "برگشتن",
    pv1_example: "Go back to your seat.",
    pv1_example_fa: "به صندلی‌ات برگرد.",
    pv2: "Give back",
    pv2_fa: "پس دادن",
    pv2_example: "Give back my book, please.",
    pv2_example_fa: "لطفاً کتابم را پس بده."
  },
  {
    word: "Bad",
    translation: "بد",
    definition_en: "Not good.",
    collocation: "Bad habit",
    collocation_fa: "عادت بد",
    collocation_example: "Smoking is a bad habit.",
    collocation_example_fa: "سیگار کشیدن یک عادت بد است.",
    pv1: "Feel for",
    pv1_fa: "دلسوزی کردن برای شرایط بد کسی",
    pv1_example: "I feel for him; he is in a bad spot.",
    pv1_example_fa: "دلم برایش می‌سوزد؛ در وضعیت بدی است.",
    pv2: "Turn out",
    pv2_fa: "از آب درآمدن / نتیجه دادن (بد)",
    pv2_example: "The weather turned out bad.",
    pv2_example_fa: "هوا بد از آب درآمد."
  },
  {
    word: "Bag",
    translation: "کیف",
    definition_en: "Something used to carry things.",
    collocation: "School bag",
    collocation_fa: "کیف مدرسه",
    collocation_example: "My school bag is heavy.",
    collocation_example_fa: "کیف مدرسه من سنگین است.",
    pv1: "Pack up",
    pv1_fa: "جمع کردن وسایل در کیف",
    pv1_example: "Pack up your bags for the trip.",
    pv1_example_fa: "کیف‌هایتان را برای سفر ببندید (جمع کنید).",
    pv2: "Put away",
    pv2_fa: "سر جای خود گذاشتن",
    pv2_example: "Put away your bag in the closet.",
    pv2_example_fa: "کیفت را در کمد بگذار."
  },
  {
    word: "Ball",
    translation: "توپ",
    definition_en: "A round object used in games.",
    collocation: "Tennis ball",
    collocation_fa: "توپ تنیس",
    collocation_example: "The tennis ball is yellow.",
    collocation_example_fa: "توپ تنیس زرد است.",
    pv1: "Throw away",
    pv1_fa: "دور انداختن",
    pv1_example: "Throw away the old ball.",
    pv1_example_fa: "توپ قدیمی را دور بینداز.",
    pv2: "Kick around",
    pv2_fa: "توپ را به این طرف و آن طرف شوت کردن",
    pv2_example: "Let's kick the ball around.",
    pv2_example_fa: "بیا توپ را به این طرف و آن طرف شوت کنیم."
  },
  {
    word: "Bank",
    translation: "بانک",
    definition_en: "A place to keep your money.",
    collocation: "Bank account",
    collocation_fa: "حساب بانکی",
    collocation_example: "I want to open a bank account.",
    collocation_example_fa: "می‌خواهم یک حساب بانکی باز کنم.",
    pv1: "Pay back",
    pv1_fa: "پس دادن بدهی (به بانک)",
    pv1_example: "I must pay back the bank loan.",
    pv1_example_fa: "من باید وام بانک را پس بدهم.",
    pv2: "Save up",
    pv2_fa: "پس‌انداز کردن",
    pv2_example: "Save up your money in the bank.",
    pv2_example_fa: "پول‌هایت را در بانک پس‌انداز کن."
  },
  {
    word: "Base",
    translation: "پایه / اساس",
    definition_en: "The lowest part of something.",
    collocation: "Main base",
    collocation_fa: "پایگاه اصلی",
    collocation_example: "This city is our main base.",
    collocation_example_fa: "این شهر پایگاه اصلی ماست.",
    pv1: "Base on",
    pv1_fa: "بر پایه چیزی بودن",
    pv1_example: "The movie is based on a book.",
    pv1_example_fa: "فیلم بر پایه یک کتاب است.",
    pv2: "Build on",
    pv2_fa: "بنا کردن بر روی پایه",
    pv2_example: "Build your house on a strong base.",
    pv2_example_fa: "خانه‌ات را روی یک پایه محکم بنا کن."
  },
  {
    word: "Bed",
    translation: "تخت خواب",
    definition_en: "A place to sleep.",
    collocation: "Single bed",
    collocation_fa: "تخت یک نفره",
    collocation_example: "I have a single bed.",
    collocation_example_fa: "من یک تخت یک نفره دارم.",
    pv1: "Get out of",
    pv1_fa: "خارج شدن از (تخت)",
    pv1_example: "Get out of bed now!",
    pv1_example_fa: "همین الان از تخت بیا بیرون!",
    pv2: "Make the bed",
    pv2_fa: "مرتب کردن تخت",
    pv2_example: "I make my bed every morning.",
    pv2_example_fa: "من هر روز صبح تختم را مرتب می‌کنم."
  },
  {
    word: "Begin",
    translation: "شروع کردن",
    definition_en: "To start something.",
    collocation: "Begin a journey",
    collocation_fa: "شروع یک سفر",
    collocation_example: "We begin our journey today.",
    collocation_example_fa: "ما امروز سفرمان را شروع می‌کنیم.",
    pv1: "Start over",
    pv1_fa: "دوباره از اول شروع کردن",
    pv1_example: "Let's begin and start over.",
    pv1_example_fa: "بیا شروع کنیم و از اول انجامش بدیم.",
    pv2: "Set off",
    pv2_fa: "راه افتادن / شروع سفر",
    pv2_example: "Begin the trip and set off early.",
    pv2_example_fa: "سفر را شروع کن و زود راه بیفت."
  },
  {
    word: "Behavior",
    translation: "رفتار",
    definition_en: "The way you act.",
    collocation: "Good behavior",
    collocation_fa: "رفتار خوب",
    collocation_example: "She has very good behavior.",
    collocation_example_fa: "او رفتار بسیار خوبی دارد.",
    pv1: "Act out",
    pv1_fa: "رفتار بد نشان دادن (ناشی از عصبانیت)",
    pv1_example: "Don't act out in class.",
    pv1_example_fa: "در کلاس رفتار بد نشان نده.",
    pv2: "Keep up",
    pv2_fa: "ادامه دادن (رفتار خوب)",
    pv2_example: "Keep up your good behavior.",
    pv2_example_fa: "رفتار خوبت را ادامه بده."
  },
  {
    word: "Behind",
    translation: "پشت / عقب",
    definition_en: "At the back of something.",
    collocation: "Behind the door",
    collocation_fa: "پشت در",
    collocation_example: "The cat is behind the door.",
    collocation_example_fa: "گربه پشت در است.",
    pv1: "Fall behind",
    pv1_fa: "عقب افتادن (از برنامه یا دیگران)",
    pv1_example: "Don't fall behind in your lessons.",
    pv1_example_fa: "از درس‌هایت عقب نیفت.",
    pv2: "Stay behind",
    pv2_fa: "عقب ماندن / توقف در جایی بعد از رفتن بقیه",
    pv2_example: "I will stay behind to finish work.",
    pv2_example_fa: "من عقب می‌مانم (اینجا می‌مانم) تا کار را تمام کنم."
  }
];
